// Skill names enum — Calvin D'Souza's Arsenal
export const SkillNames = {
  // Frontend
  REACT: "react",
  NEXTJS: "nextjs",
  TYPESCRIPT: "ts",
  TAILWIND: "tailwind",
  THREEJS: "threejs",
  GSAP: "gsap",
  // Cybersecurity
  PENTESTING: "pentesting",
  CTF: "ctf",
  BURPSUITE: "burpsuite",
  LINUX: "linux",
  NMAP: "nmap",
  // AI / ML
  PYTHON: "python",
  PYTORCH: "pytorch",
  LANGCHAIN: "langchain",
  HUGGINGFACE: "huggingface",
  DOCKER: "docker",
  // General / Extra (to fill up keyboard keycaps that have hardcoded names)
  JS: "js",
  HTML: "html",
  CSS: "css",
  GIT: "git",
  AWS: "aws",
  NODEJS: "nodejs",
  FIREBASE: "firebase",
};

export const SKILLS = {
  // ── FRONTEND ────────────────────────────────────────────────────────────────
  react: {
    id: 1,
    name: "react",
    label: "React",
    shortDescription: "Component architecture, hooks, and state management for modern UIs.",
    color: "#61dafb",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  nextjs: {
    id: 2,
    name: "nextjs",
    label: "Next.js",
    shortDescription: "Full-stack React — SSR, edge deployments, and file-based routing.",
    color: "#ffffff",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
  },
  ts: {
    id: 3,
    name: "ts",
    label: "TypeScript",
    shortDescription: "Type-safe codebases — generics, utility types, strict mode.",
    color: "#007acc",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
  },
  tailwind: {
    id: 4,
    name: "tailwind",
    label: "Tailwind",
    shortDescription: "Rapid UI development with a utility-first approach.",
    color: "#38bdf8",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
  },
  threejs: {
    id: 5,
    name: "threejs",
    label: "Three.js",
    shortDescription: "3D web experiences, WebGL rendering, and custom shaders.",
    color: "#ffffff",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg",
  },
  gsap: {
    id: 6,
    name: "gsap",
    label: "GSAP",
    shortDescription: "Professional-grade scroll animations and timeline control.",
    color: "#88ce02",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/greensock/greensock-plain.svg",
  },

  // ── CYBERSECURITY ───────────────────────────────────────────────────────────
  pentesting: {
    id: 7,
    name: "pentesting",
    label: "Pen Test",
    shortDescription: "Web app & network penetration testing — recon to exploitation.",
    color: "#ff4444",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
  },
  ctf: {
    id: 8,
    name: "ctf",
    label: "CTF",
    shortDescription: "Forensics, RE, web exploits — top placements on HackTheBox & NITK.",
    color: "#ff8c00",
    icon: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Kali-dragon-icon.svg",
  },
  burpsuite: {
    id: 9,
    name: "burpsuite",
    label: "Burp Suite",
    shortDescription: "Web vulnerability scanning and manual exploit crafting.",
    color: "#ff6600",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
  },
  linux: {
    id: 10,
    name: "linux",
    label: "Linux",
    shortDescription: "Kali, Ubuntu — bash scripting, system hardening, forensics.",
    color: "#ffffff",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
  },
  nmap: {
    id: 11,
    name: "nmap",
    label: "Nmap",
    shortDescription: "Network discovery, port scanning, and security auditing.",
    color: "#aaaaaa",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
  },

  // ── AI / ML ─────────────────────────────────────────────────────────────────
  python: {
    id: 12,
    name: "python",
    label: "Python",
    shortDescription: "ML pipelines, scripting, automation — primary research language.",
    color: "#f7c948",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
  },
  pytorch: {
    id: 13,
    name: "pytorch",
    label: "PyTorch",
    shortDescription: "Deep learning, neural network training, YOLOv8 computer vision.",
    color: "#ee4c2c",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg",
  },
  langchain: {
    id: 14,
    name: "langchain",
    label: "LangChain",
    shortDescription: "LLM app development — RAG pipelines, multi-agent systems.",
    color: "#00c58e",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
  },
  huggingface: {
    id: 15,
    name: "huggingface",
    label: "HuggingFace",
    shortDescription: "Fine-tuning, inference, and model deployment at scale.",
    color: "#ffcc00",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
  },
  docker: {
    id: 16,
    name: "docker",
    label: "Docker",
    shortDescription: "Containerisation, compose, and multi-service deployment.",
    color: "#2496ed",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
  },

  // ── GENERAL (fills extra keycaps) ───────────────────────────────────────────
  js: {
    id: 17,
    name: "js",
    label: "JavaScript",
    shortDescription: "The language of the web — async, ES2024, and beyond.",
    color: "#f0db4f",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
  },
  html: {
    id: 18,
    name: "html",
    label: "HTML",
    shortDescription: "Semantic structure and accessibility-first markup.",
    color: "#e34c26",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
  },
  css: {
    id: 19,
    name: "css",
    label: "CSS",
    shortDescription: "Animations, grid, and custom properties — no framework needed.",
    color: "#563d7c",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
  },
  git: {
    id: 20,
    name: "git",
    label: "Git",
    shortDescription: "Version control, branching strategies, and collaborative workflows.",
    color: "#f1502f",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
  },
  aws: {
    id: 21,
    name: "aws",
    label: "AWS",
    shortDescription: "EC2, S3, Lambda — scalable cloud deployment pipelines.",
    color: "#ff9900",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg",
  },
  nodejs: {
    id: 22,
    name: "nodejs",
    label: "Node.js",
    shortDescription: "Server-side JavaScript — REST APIs, WebSocket, and microservices.",
    color: "#6cc24a",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
  },
  firebase: {
    id: 23,
    name: "firebase",
    label: "FastAPI",
    shortDescription: "High-performance Python API server — async, typed, ultra-fast.",
    color: "#009688",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg",
  },
};
